### ISSUE TITLE
Accessibility Considerations

### ISSUE THREAD

**Issue by Charlotteis** [lewiscowper/lewiscowper.github.io#2]
Cognitive Accessibility:
* Line height of at least 1.5, readability = accessibility.
* Short line lengths, when you go past 80 characters, things get harder to read and scan.
http://webaim.org/articles/evaluatingcognitive/

Make sure anything that is traditionally focusable (like links) have a `:focus` state so I can tell when I've tabbed to something. Most browsers will do a blue outline, but not all will do.

Tips:
Try and go through your site/CV with just a keyboard, using the `TAB` key.
If you have a Mac, activate VoiceOver:
* Close your eyes and listen to the page, does it make sense?
* Open and your eyes and listen, are things being read in the right order?
* You can use the arrow keys when VoiceOver is on to read text too.

:)

**Comment by Charlotteis** [comment]
Oh also, I wrote a BUNCH of stuff here:

The 'Accessibility' and 'Testing' sections would be most useful, I hope: http://var.ghost.io/how-i-built-a-website/

**Comment by lewiscowper** [comment]
That's what I've been basing my a11y and testing readings on so far. :+1:

**Comment by Charlotteis** [comment]
On my article? :o

**Comment by lewiscowper** [comment]
Yeah, lots of really good reading around there, explained in such a way that I almost got it.

**Comment by lewiscowper** [comment]
So I've discovered that <article role="article"> is somewhat redundant, because the <article> tag has the implicit role set because it's the same.

http://www.w3.org/TR/2015/WD-html51-20150506/semantics.html#the-article-element
![screen shot 2015-05-23 at 09 17 11](https://cloud.githubusercontent.com/assets/593574/7783085/8a127f8e-012c-11e5-9236-47d9b4cb7f8e.png)

Just for your/my information. :)

**Comment by Charlotteis** [comment]
I'm glad it was of use :)

Hmm that's interesting. I don't trust browsers though, this is kind of my sentiment: http://html5doctor.com/using-aria-in-html/#comment-221615

**Comment by lewiscowper** [comment]
Also, you can check out the latest released version (https://github.com/lewiscowper/lewiscowper.github.io/releases/tag/v1.0.0) at http://hi.lewis.red and hopefully I've addressed anything raised.

I went through the VoiceOver training and then navigated around the site with it. It's super cool. :+1:

**Comment by Charlotteis** [comment]
:tada:
